ERROR 2013-10-10 23:24:37,131 middleware 30438 139661484324608 Uncaught exception: Cannot resolve keyword 'emp_website_type' into field. Choices are: description, employer, id, txt, url, website_type
Traceback (most recent call last):
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/oleg/code/web-serpng/code/serpng/employer_pages/views/profile.py", line 42, in profile
    'employer_names_top_cities_jobs': names_and_top_cities_for_employer(emp),
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/loader_tags.py", line 156, in render
    return self.render_template(self.template, context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/loader_tags.py", line 138, in render_template
    output = template.render(context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/template/defaulttags.py", line 148, in render
    len_values = len(values)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/query.py", line 90, in __len__
    self._result_cache = list(self.iterator())
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/query.py", line 301, in iterator
    for row in compiler.results_iter():
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 830, in execute_sql
    sql, params = self.as_sql()
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 75, in as_sql
    ordering, ordering_group_by = self.get_ordering()
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 394, in get_ordering
    self.query.model._meta, default_order=asc):
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 420, in find_ordering_name
    field, col, alias, joins, opts = self._setup_joins(pieces, opts, alias)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 453, in _setup_joins
    opts, alias, False)
  File "/home/oleg/virtualenv/serpng/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1325, in setup_joins
    "Choices are: %s" % (name, ", ".join(names)))
FieldError: Cannot resolve keyword 'emp_website_type' into field. Choices are: description, employer, id, txt, url, website_type
